services:
  frontend:
    build: ./packages/spectra_inspector/
    ports:
      - "8050:8050"
    environment:
      # Include development dependencies when working locally
      - UV_NO_DEV=0
    user: root
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./packages/spectra_inspector/uv.lock

  fastapi:
    # Build the image from the Dockerfile in the current directory
    build: ./packages/spectra_inspector_server/
    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"
    environment:
      # Include development dependencies when working locally
      UV_NO_DEV: 0
      SPECTRA_INSPECTOR_DOCKER_FASTAPI_WORKERS: ${SPECTRA_INSPECTOR_DOCKER_FASTAPI_WORKERS:-1}

    # Run as root during development so the environment is mutable
    # Alternatively, you could set `UV_PROJECT_ENVIRONMENT` to a path owned by the non-root user
    user: root
    volumes:
      - TorresSamplesFromBox:${SPECTRA_INSPECTOR_DATA_ROOT}
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./packages/spectra_inspector_server/uv.lock

volumes:
  TorresSamplesFromBox:
    driver: local
    driver_opts:
      type: none
      device: ${SPECTRA_INSPECTOR_HOST_DATA_ROOT}
      o: bind
