[project]
name = "spectra_inspector_manager"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["spectra_inspector", "spectra_inspector_server"]

[tool.uv.sources]
spectra_inspector = { workspace = true }
spectra_inspector_server = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
